petstagram/petstagram/photos/urls.py
from django.urls import path, include

from petstagram.photos import views

urlpatterns = (
    path('add/', views.create_photo, name='create_photo'),
    path('<int:pk>/', include([
        path('', views.photo_details, name='photo_details'),
        path('edit/', views.photo_edit_page, name='edit_photo'),
        path('delete/', views.photo_delete, name='delete_photo'),
    ])),
)

petstagram/petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("petstagram.common.urls")),
    path("accounts/", include("petstagram.accounts.urls")),
    path("pets/", include("petstagram.pets.urls")),
    path("photos/", include("petstagram.photos.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

petstagram/petstagram/photos/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from petstagram.pets.models import Pet


class Photo(models.Model):
    MAX_DESCRIPTION_LENGTH = 300
    MIN_DESCRIPTION_LENGTH = 10
    MAX_LOCATION_LENGTH = 30

    photo = models.ImageField(
        upload_to="media",

    )

    description = models.TextField(
        max_length=MAX_DESCRIPTION_LENGTH,
        validators=(
            MinLengthValidator(
                MIN_DESCRIPTION_LENGTH
            ),
        ),
        blank=True,
        null=True,
    )

    location = models.CharField(
        max_length=MAX_LOCATION_LENGTH,
        blank=True,
        null=True
    )

    pets = models.ManyToManyField(
        Pet,
        blank=True
    )

    date_of_publication = models.DateField(
        auto_now=True
    )

petstagram/petstagram/photos/forms.py
from django import forms

from petstagram.photos.models import Photo


class PhotoCreteForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = '__all__'


class PhotoEditForm(forms.ModelForm):
    class Meta:
        model = Photo
        exclude = ('photo',)

petstagram/petstagram/photos/views.py
from django.shortcuts import render, redirect

from petstagram.photos.forms import PhotoCreteForm
from petstagram.photos.models import Photo


def create_photo(request):
    form = PhotoCreteForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        form.save()
        return redirect('photo_details', form.instance.pk)

    context = {
        'form': form
    }
    return render(request, "photos/photo-add-page.html", context)


def photo_details(request, pk):
    context = {
        'pet_photo': Photo.objects.get(pk=pk)

    }
    return render(request, "photos/photo-details-page.html", context)


def photo_edit_page(request, pk):
    context = {}
    return render(request, "photos/photo-edit-page.html", context)


def photo_delete(request, pk):
    photo = Photo.objects.get(pk=pk)
    photo.delete()
    return redirect('index')

petstagram/templates/photos/photo-add-page.html
{% extends 'base.html' %}

{% load static %}

{% block main_content %}

    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <!-- Start Add Photo Form -->
        <form action="{% url 'create_photo'%}" method="post" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <!-- Add Photo Button -->
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
        <!-- End Add Photo Form -->
    </div>
    <!-- End Add Photo Section -->
{% endblock %}

petstagram/templates/photos/photo-details-page.html
{% extends 'base.html' %}

{% load static %}

{% block main_content %}
    
    <div class="container">
        <div class="col-9">

            <!-- Start Pet Photo Post Section -->
            {% include 'partials/pet_photo_list_item.html' with photo=pet_photo %}
            <!-- End Pet Photo Post Section -->

        </div>
    </div>

{% endblock %}

petstagram/templates/photos/photo-edit-page.html
{#{% extends 'base.html' %}#}
{##}
{#{% load static %}#}
{##}
{#{% block main_content %}#}
{##}
{#    <!-- Starts Edit Photo Section -->#}
{#    <div class="edit-delete edit-photo">#}
{#        <h2>Edit photo</h2>#}
{##}
{#        <!-- Starts Edit Photo Form -->#}
{#        <form action="">#}
{##}
{#            <p>#}
{#                <label for="id_description">Description:</label>#}
{#                <input type="text" value="Sasho is an Axolotl">#}
{#            </p>#}
{##}
{#            <p>#}
{#                <label for="id_description">Location:</label>#}
{#                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"#}
{#                       value="Bansko, Bulgaria">#}
{#            </p>#}
{##}
{#            <p>#}
{#                <label for="pets">Tag Pets:</label>#}
{##}
{#                <select name="pets" id="id_tagged_pets" multiple>#}
{#                    <option selected>Sasho</option>#}
{#                    <option>Perry</option>#}
{#                    <option>Bucky</option>#}
{#                    <option>Steve</option>#}
{#                </select>#}
{#            </p>#}
{##}
{#            <!-- Edit Photo Button -->#}
{#            <button class="edit-btn" type="submit">Edit Photo</button>#}
{#        </form>#}
{#        <!-- End Edit Photo Form -->#}
{##}
{#    </div>#}
{#    <!-- End Edit Photo Section -->#}
{##}
{#{% endblock %}#}

{% extends 'base.html' %}

{% load static %}

{% block main_content %}
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <form action="{% url 'edit photo' pk=object.pk %}" method="post" enctype="multipart/form-data">
            {{ form.as_p }}

            <button class="edit-btn" type="submit">Edit Photo</button>

            {% csrf_token %}
        </form>
    </div>
{% endblock %}