petstagram/petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("petstagram.common.urls")),
    path("accounts/", include("petstagram.accounts.urls")),
    path("pets/", include("petstagram.pets.urls")),
    path("photos/", include("petstagram.photos.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

petstagram/petstagram/common/models.py
from django.contrib.auth import get_user_model
from django.db import models

from petstagram.photos.models import Photo

UserModel = get_user_model()


class Comment(models.Model):
    MAX_TEXT_LENGTH = 300

    text = models.TextField(
        max_length=MAX_TEXT_LENGTH,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    modified_at = models.DateTimeField(
        auto_now=True,
    )

    pet_photo = models.ForeignKey(
        Photo,
        on_delete=models.CASCADE,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )

    def __str__(self):
        return self.text


class PhotoLike(models.Model):
    pet_photo = models.ForeignKey(
        Photo,
        on_delete=models.DO_NOTHING,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True,
    )

petstagram/templates/partials/pet_photo_list.html
{% load static %}

{% for photo in photo_list %}
    
    {% include 'partials/pet_photo_list_item.html' with photo=photo %}

{% empty %}
    <img class="no-posts" src="{% static 'images/no_posts.png' %}" alt="no posts image">

{% endfor %}

petstagram/templates/partials/pet_photo_list_item.html
{% load static %}


<div class="card">

    <div class="top">
        <div class="userDetails">
            <a href="{% url "details_profile" pk=1 %}">
                <div class="profilepic">
                    <div class="profile_img">
                        <div class="image">
                            <img src="{% static 'images/person.png' %}" alt="img8">
                        </div>
                    </div>
                </div>
            </a>
            <h3>
                <a href="{% url "details_profile" pk=1 %}">
                    Diyan Kalaydzhiev
                    <!-- else -->
                </a>
                <br>
                <!-- if the photo has location -->
                <span>{{ photo.location }}</span>
            </h3>
        </div>
    </div>
    <!-- End User Details and Image Location -->

    <!-- Start Pet Photo -->
    <div class="imgBx" id="photo-{{ photo.pk }}">
        <img src="{{ photo.photo.url }}" alt="post" class="cover">
    </div>
    <!-- End Pet Photo -->

    <!-- Start Like and Share Buttons -->
    <div class="bottom">
        <div class="actionBtns">
            <div class="left">
                <!-- Start Like Button -->
                <span class="heart">
                    <a href="{% url 'like_pet_photo' pk=photo.pk %}">
                        {% if photo.photolike_set.count > 0 %}
                            <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                        {% else %}
                            <i class="fa-regular fa-heart"></i>
                        {% endif %}
                    </a>
                </span>
                <!-- End Like Button -->

                <!-- Start Share Button -->
                <a href="#">
                    <i class="fa-solid fa-share"></i>
                </a>
                <!-- End Share Button -->

            </div>
        </div>
        <!-- End Like and Share Buttons -->

        <!-- Number of Likes per Photo -->
        <p class="likes">{{ photo.photolike_set.count }}</p>


        {% for pet in photo.pets.all %}
            <a href="{% url "details_pet" username="Viktor" pet_slug=pet.slug %}">
                <p class="message">
                    <b>{{ pet.name }}</b>
                </p>
            </a>
        {% endfor %}


        <!-- Link to Photo Details Page -->
        <a href="{% url "photo_details" pk=photo.pk %}">
            <h4 class="details">See details</h4>
        </a>

        <!-- Date of Publication -->
        <h5 class="postTime">{{ photo.date_of_publication|date:"d/m/Y" }}</h5>
        {% if photo.comment_set.last %}
            <h5 class="comments">Comments: {{ photo.comment_set.last }}</h5>
        {% else %}

        {% endif %}

        <!-- Start Add Comments Section -->
        <div class="addComments">

            <!-- Start Add Comments Form -->
            <form method="post" action="{% url 'add_comment' photo.id %}">
                {% csrf_token %}
                {{ comment_form }}
                <button type="submit">Post</button>
            </form>
            <!-- End Add Comments Form -->

        </div>
        <!-- End Add Comments Section -->

    </div>
</div>